version: '3.8'

services:
  # 1. Veritabanı Servisi
  postgres:
    image: postgres:15
    container_name: repvision_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: repvision_db  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - repvision-network

  # 2. Mesaj Kuyruğu Servisi
  rabbitmq:
    image: rabbitmq:3-management
    container_name: repvision_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - repvision-network

volumes:
  postgres_data:

networks:
  repvision-network:
    driver: bridge